ansible_inventory_path: null
ansible_inventory_source: null
clusters: {}
discovery_complete: true
discovery_timestamp: '2026-03-19T11:52:27.730534'
hosts_file: /tmp/tmpot4qc7cy.txt
nodes:
  hana03:
    ansible_host: null
    ansible_reachable: false
    ansible_user: null
    hostname: hana03
    last_checked: '2026-03-19T11:52:24.474162'
    preferred_method: ssh
    sosreport_path: null
    ssh_reachable: true
    ssh_user: root
sosreport_directory: null
